#!/bin/sh
set -eu

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}"
IMG="$CACHE/i3lock/lock-wall.png"

[ -r "$IMG" ] || exit 1

i3lock \
		--color=000000 \
		--clock \
		--time-pos x+170:y+h-150\
		--time-color=ffffff \
		--time-size=120 \
		--time-font="Segoe UI Light" \
		--time-str="%H:%M" \
		--date-color=ffffff \
		--date-size=45 \
		--date-pos x+170:y+h-80\
		--date-font="Segoe UI Light" \
		--date-str="%a, %Y-%m-%d" \
		-i "$IMG"
