#!/bin/sh
set -eu

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/i3lock"
mkdir -p "$CACHE"
OUT="$CACHE/lock-wall.png"

IN=""
BLUR=""

while getopts "i:o:b:" opt; do
    case "$opt" in
        i) IN="$OPTARG" ;;
        o) OUT="$OPTARG" ;;
        b) BLUR="$OPTARG" ;;
        *) echo "usage: $0 [-i input] [-o output] [-b blur]"; exit 1 ;;
    esac
done
shift $((OPTIND-1))

: "${IN:?input image required}"

RES=$(xdpyinfo | awk '/dimensions:/ {print $2}')

ARGS=""
[ -n "$BLUR" ] && ARGS="-blur $BLUR"

magick "$IN" -resize "${RES}"^ -gravity center -extent "${RES}" $ARGS "$OUT"
