#!/bin/sh
set -eu

: "${CACHE:?CACHE must be set by caller}"

BOX="$CACHE/box.png"

convert \
  -font DejaVu-Sans \
  \
  \( -background none \
     -pointsize 120 \
     label:"88:88:88" \
     -pointsize 32 \
     label:"Wednesday 88 8888" \
     -append \
     -border 22 \
  \) \
  \
  -clone 0 \
  -fill "#80808080" \
  -colorize 100 \
	-alpha set \
  -channel A -evaluate set 50% +channel \
  \
  -delete 0 \
  "$BOX"

