#!/bin/sh
set -eu

: "${CACHE:?CACHE must be set by caller}"

IN="${1:?input image required}"
OUT="${2:?output image required}"

BOX="$CACHE/box.png"

convert "$IN" \
		-resize 2560x1440^ \
		-gravity center \
		-extent 2560x1440 \
		-blur 0x6 \
		\( "$BOX" -gravity center -geometry +0-50 \) \
		-composite \
		"png:$OUT"
